"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Nav from "@/components/elements/Nav";
import { useSession } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {

  const pathname = typeof window !== "undefined" ? window.location.pathname : "";

  const shouldHideNav = ["/auth/login", "/auth/signup"].includes(pathname);
  
  return (
    <html lang="en"
      style={{ ['--nav-height' as any]: '4rem' }}
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <SessionProvider>
          {!shouldHideNav && <Nav />}
          <main className="relative z-10">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
